### ISSUE TITLE
Custom bitfield types (signed fields)?

### ISSUE THREAD

**Issue by nyanpasu64** [preshing/cpp11-on-multicore#11]
If you have a 64-bit bitfield, is it possible to mark certain fields as signed, for example by passing in a custom return type of int16_t?

**Comment by preshing** [comment]
You could probably do this. Use `std::is_signed<T>::value` to determine if `T` is signed. You can use that in `operator T()` and, if it's signed, sign-extend the most significant bit. Here are a few possible ways to do that: https://stackoverflow.com/questions/5814072/sign-extend-a-nine-bit-number-in-c
